### ISSUE TITLE
way to translate "dismiss"-button

### ISSUE THREAD

**Issue by bohrsty** [chadly/react-bs-notifier#13]
hello and thank you for your library...
i'm going to use it in my project and the only thing i couldn't find, is a way to translate (or just change the text) of the html-title (the text if you hover over the x) of the dismiss-button in the notification.
is there a way that i didn't find in the docs and examples, or is it not possible at the moment? if not, that would be a nice feature...

regards bohrsty

**Comment by chadly** [comment]
@mdarens implemented it in #14. It is on npm as v3.2.0
