### ISSUE TITLE
Maximum number of visible items 

### ISSUE THREAD

**Issue by naxsooley** [chadly/react-bs-notifier#16]
We should have an option to allow maximum number of alerts in container.

We might like to show only 5 last alerts, not all.

Please provide an option to achieve this.

**Comment by chadly** [comment]
This is something you can implement in your application's logic. The `AlertList` simply takes an array of `alerts` and renders them. You can easily accomplish what you want by limiting what you pass to `AlertList`:

``` js
<AlertList alerts={myAlerts.slice(0, 5)} />
```

which would always only render the first 5 elements of `myAlerts`.
