### ISSUE TITLE
Toetag dependency issue

### ISSUE THREAD

**Issue by frankolson** [chadly/react-bs-notifier#26]
I am getting the following error when using this library, and am absolutely stumped.

```
Module not found: Error: Can't resolve './lib/bootstrap-variables' in '/path/to/node_modules/toetag'
```

When looking into the [toetag](https://github.com/civicsource/toetag/blob/master/index.js) library it looks like it is referencing a file not in its source code. I am posting this here instead of that repo because it looks like you all made that library anyways, and there is way more activity here.

**Comment by mdarens** [comment]
What module bundler are you using? toetag puts a bootstrap-variables.json in lib when publishing. If your module bundler doesn't have json loading configured that might be the cause.

**Comment by frankolson** [comment]
I am using yarn and webpack. I did add webpack's [json-loader](https://github.com/webpack-contrib/json-loader), but that did not seem to do the trick.

**Comment by frankolson** [comment]
Alright so I looked into it more and it looks like webpack has json loadin on by default. This was confirmed because when I updated toetag from this:

```javascript
module.exports = {
  'bootstrap': require('./lib/bootstrap-variables')
} 
```
to this:

```javascript
module.exports = {
  'bootstrap': require('./lib/bootstrap-variables.json')
}
```

(note the extension change) it started working. Is there a reason why the extension was left out?

**Comment by chadly** [comment]
Did you override your [`resolve.extensions`](https://webpack.js.org/configuration/resolve/#resolve-extensions)? Webpack 2 is set to load json files by default extensionless. But if you override `resolve.extensions`, you will need to make sure to include `.json` in there.

**Comment by frankolson** [comment]
Awesome that was it, thanks @chadly!

**Comment by joetidee** [comment]
What harm is there in adding .json onto the end of 'bootstrap-variables' ?

**Comment by chadly** [comment]
It goes against [style guide / lint rules](https://github.com/civicsource/eslint-config-civicsource). That being said, I would happily accept a PR that adds the extension and disables that lint rule. You'd have to open it on [civicsource/toetag](https://github.com/civicsource/toetag), though.

**Comment by joetidee** [comment]
Done
