### ISSUE TITLE
AlertList invalid prop warning when using mobx ObservableArray for alerts array

### ISSUE THREAD

**Issue by FabriceReynolds** [chadly/react-bs-notifier#28]
I get the following warning when setting the alerts prop of the AlertList to an observable array:

> Warning: Failed prop type: Invalid prop `alerts` of type `object` supplied to `AlertList`, expected an array.

However the good news is that it seems to work okay.

**Comment by chadly** [comment]
I am not familiar with mobx observables. Do they support the [prop-type validators](https://github.com/reactjs/prop-types) that react uses?

If not, like you said, it is just a warning.

**Comment by FabriceReynolds** [comment]
Thanks @chadly. I presume so but I guess it's because the ObservableArray isn't really an array so would fail an isArray check for example. 

After a bit of searching here is what MobXs website says about ObservableArray.

> Due to limitations of native arrays in ES5 observable.array will create a faux-array (array-like object) instead of a real array. In practice, these arrays work just as fine as native arrays and all native methods are supported, including index assignments, up-to and including the length of the array.
> 
> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.

I can't use a shallow copy as suggested here as it would no longer be observable. I just wanted to pass on the info as others may have similar warnings with array-like objects.

**Comment by chadly** [comment]
Thanks @FabriceReynolds
