### ISSUE TITLE
Like doing a line jump in the props of the message to make the following listing in an AlertList

### ISSUE THREAD

**Issue by nato90** [chadly/react-bs-notifier#29]
example:

The system detected the following problems:

● The key is invalid.
● The accounting key is invalid.
● Status is invalid.

Note: Try to use a "\n" and a br but do not respect it

**Comment by mdarens** [comment]
Hi! If I understand correctly, you're trying to format a message in an alert with whitespace.

If so, `message` can take arbitrary JSX, so you can either feed it markup which renders block level elements, or give a `className` or `styles` to an element in `message` where `white-space` is set to `pre` or `pre-wrap`. This way your whitespace will be visible in the output.
