### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by inzamam-iqbal** [chadly/react-bs-notifier#30]
I tried the following code 

```js
constructor(props) {
		super(props);
		this.state = {
			alerts :[{
				id: 1,
				type: "info",
				message: "Hello, world",
			}, {
				id: 2,
				type: "success",
				message: "Oh, hai"
			}]
		}
}

render(){
  <AlertList
	position={"top-right"}
	alerts={this.state.alerts}
        timeout=2000
	dismissTitle="Begone!"
	onDismiss={() => { }}/>
}
```

everything works as expected, but the timeout and close button doesn't work.
I also tried putting timeout individually for each alert.

**Comment by chadly** [comment]
The timeout and close button simply call the `onDismiss` function you pass in as a prop. Your implementation doesn't do anything right now. Try putting a `console.log` in there and you'll see it is being called.
