### ISSUE TITLE
Cannot find .json file

### ISSUE THREAD

**Issue by joetidee** [chadly/react-bs-notifier#32]
After installing this package I recieved the following error:

```
ERROR in ./~/toetag/index.js
Module not found: Error: Can't resolve './lib/bootstrap-variables' in '/tidee/tidee-au/packages/tidee-au-client/node_modules/toetag'
```

I imagine that this is because the .json extension does not exist in index.js - can you change this?

**Comment by chadly** [comment]
See #26
