### ISSUE TITLE
v4.4.0 loses styling on notifications

### ISSUE THREAD

**Issue by gtwilliams03** [chadly/react-bs-notifier#35]
I upgraded my project to v4.4.0 from v4.3.2 and it lost the CSS formatting on the notifications.  I reverted back to v4.3.2 and it came back - see the screenshots below.  Any ideas?

`v4.4.0`
<img width="149" alt="react-bs-notifier-screenshot" src="https://user-images.githubusercontent.com/1564628/31296070-07c172e0-aaaf-11e7-80c2-0fa65de991a7.png">

`v4.3.2`
<img width="215" alt="react-bs-notifier-screenshot-4-3-2" src="https://user-images.githubusercontent.com/1564628/31296069-07c0048c-aaaf-11e7-97a0-77d60c17da0f.png">

**Comment by chadly** [comment]
Fixed in [`v4.4.1`](https://github.com/chadly/react-bs-notifier/releases/tag/v4.4.1%2B1)

**Comment by gtwilliams03** [comment]
```
WARNING in ./node_modules/react-bs-notifier/es/alert/styles.js
7:37-53 "export 'transitionStyles' was not found in '../alert-transition'
```

**Comment by gtwilliams03** [comment]
Got this webpack error when I built with `v4.4.1`?

**Comment by gtwilliams03** [comment]
It works - but throws that error on running in development.
