### ISSUE TITLE
Dispatch of dismiss alert using timeout feature gets called continuously

### ISSUE THREAD

**Issue by LoriTillery** [chadly/react-bs-notifier#45]
Similar to @themortalcoil's comment posted on issue #22, i am finding that my dismissAlert dispatch is called continuously at the same interval the as my alert's timeout value.  I can see in the state that the first dispatched dismissalert removes the alert from the array; however, the onDismiss function keeps dispatching the action at a rate equal to the timeout value and  continues dispatching until i close the tab. 

BTW - I've been using the library for a few months but just noticed this issue after i upgraded to React 16 and Redux 3.7.2  2 weeks ago.

**Comment by LoriTillery** [comment]
Finally, I removed this package and re-added it and now it works.  according to my yarn.lock i moved from 4.4.4 to 4.4.5.  that seems to have correct this issue.  feel free to close.

**Comment by chadly** [comment]
Great, thanks. Must have been related to #43 which was fixed with #44.
