### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by MonkeyDo** [chadly/react-bs-notifier#81]
Hello!
First of all thank you for your work on this library. We use it over at [ListenBrainz](https://github.com/metabrainz/listenbrainz-server)

I recently started preparing to migrate our project to React 18, and saw that the peer dependency requirement of react-bs-notifier for react is < 18.

With React 18 published at the beginning of the year, and being the next big version that changed a lot of internal APIs, I was wondering if you have any plans for extending support to React 18+

**Comment by chadly** [comment]
nice! glad to hear it's a helpful project. that really helps with motivation to keep this up.

> I was wondering if you have any plans.

I have so many plans and desires and intentions...not a lot of time though.

It shouldn't be too difficult to upgrade this project with the latest. Just needs some TLC.

If you had the energy to do a PR, I'd be happy to review, merge, and do a new release.

**Comment by MonkeyDo** [comment]
Let me know if the choices I made work for you; happy to change them as required.

**Comment by MonkeyDo** [comment]
Hi @chadly !
Please let me know if you think you'll have time to look at the PR soon.
Please don't take this as a nag or a push, I can point to my fork temporarily if you need more time, that's not an issue. Just figuring out my planning :)

**Comment by chadly** [comment]
fixed in [v7.0](https://github.com/chadly/react-bs-notifier/releases/tag/v7.0.0).

thanks again!

**Comment by MonkeyDo** [comment]
My pleasure! And thank you for the quick turnaround!
